name: My First GitHub Actions Workflow

on:
  workflow_dispatch:
  pull_request:
      branches:
        - feature/perfomance-test
jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World!"

      - name: Print Date
        run: date

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la
