name: Performance Test

on:
  workflow_dispatch:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Taurus
        run: |
          pip install bzt

      - name: Install k6
        run: |
          sudo gpg -k
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install k6
      - name: Verify k6 installation
        run: |
          k6 version
      
      - name: Verify project structure
        run: |
          pwd
          ls -R
      
      - name: Run k6 directly
        run: |
          k6 run k6/login-test.js
          
      - name: Install Taurus
        run: |
          python -m pip install bzt
      
      - name: Check installed versions
        run: |
          python -m pip show bzt
          k6 version


      - name: Check versions
        run: |
          bzt --version
          k6 version
          
      - name: Execute Taurus Test
        run: |
          run: bzt -v taurus/taurus.yml

      - name: Upload Taurus Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: taurus-artifacts
          path: /home/runner/work/PerfomanceTestPOC/PerfomanceTestPOC/2026-07-21_15-40-14.075635          
